name: "Terraform deployment"
on: 
  push:
    branches:
      - tf/destroy
  pull_request:
    branches:
      - tf/destroy
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs: 
  terraform: 
    name: "Terraform provision"
    runs-on: ubuntu-latest
    steps:
      #check out the terraform repo code 
      - name: 'Checkout tf source code'
        uses: actions/checkout@v3
      
      # setup terraform cli 
      - name: "TF enginee Setup"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5
          terraform_wrapper: false

      - name: "Create namespace"
        run: "terraform workspace new dev"
        continue-on-error: true
        
      - name: "Select namespace"
        run: "terraform workspace select dev"
        continue-on-error: true

      - name: "Init tf"
        run: |
          terraform init -backend-config=dev.conf

      - name: "Destroy the resources"
        run: "terraform destroy -var-file=./envs/dev.tfvars --auto-approve"